---
version: "3"

services:

  bookshelves:
    build:
      dockerfile: deploy/docker/Dockerfile
      context: ../../
    environment:
      BOOKSHELVES_ENVIRONMENT: production
      BOOKSHELVES_STATIC_URL: http://${NGINX_HOST:-127.0.0.1}/static/
      BOOKSHELVES_MEDIA_URL: http://${NGINX_HOST:-127.0.0.1}/media/
      BOOKSHELVES_ALLOWED_HOSTS: "['143.244.145.69', '0.0.0.0', '127.0.0.1', 'localhost']"
      BOOKSHELVES_DATABASES_PRODUCTION_HOST: db
      BOOKSHELVES_DATABASES_PRODUCTION_USER: bookshelves
      BOOKSHELVES_DATABASES_PRODUCTION_PASSWORD: "!@#)(*D"
    ports:
      - "8000:8000"
    volumes:
      - ../../bookshelves/static/:/opt/bookshelves/static/
      - ../../bookshelves/media/:/opt/bookshelves/media/
    restart: on-failure
    depends_on:
      - db
    command: "./init.sh --with-delay"

  db:
    image: postgres
    volumes:
      - ./db/:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: bookshelves
      POSTGRES_USER: bookshelves
      POSTGRES_PASSWORD: "!@#)(*D"
    restart: unless-stopped

  ws:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ../../bookshelves/static/:/www/data/static/
      - ../../bookshelves/media/:/www/data/media/
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
    depends_on:
      - bookshelves
